/**
 * Very simple program to spit out a random username in the form of [Adjective][Noun][Number]. Just execute the
 * program and pull the username from stdout.
*/

#include <time.h>
#include <stdio.h>
#include <ctype.h> // for toupper()
#include <stdlib.h> // for rand(), itoa()
#include <string.h>
#include <math.h>
#include <stdbool.h> // for bool
#include <getopt.h> // for getopt_long()

char *adjectives[] = {
    "able", 
    "abrasive",
    "abrupt", 
    "absent-minded", 
    "abusive", 
    "accepting", 
    "accessible",
    "accident-prone", 
    "accommodating",
    "accomplished", 
    "accountable", 
    "accurate",
    "action-oriented",
    "active", 
    "adaptable", 
    "admirable", 
    "adventuresome", 
    "adventurous",
    "aesthetic",
    "affable",
    "affected",
    "affectionate",
    "affirming",
    "afraid",
    "aggressive",
    "agnostic", 
    "agonizing", 
    "agreeable", 
    "aimless", 
    "airy", 
    "alert", 
    "allocentric", 
    "alluring",
    "alone", 
    "aloof", 
    "altruistic", 
    "ambitious", 
    "amiable", 
    "amicable", 
    "amoral", 
    "amusing", 
    "anal-retentive",
    "analytical", 
    "angry",
    "animated",
    "annoyed",
    "annoying",
    "anticipative",
    "antisocial",
    "anxious",
    "apathetic",
    "apologetic",
    "appreciative",
    "apprehensive",
    "approachable",
    "arbitrary",
    "argumentative",
    "aristocratic",
    "arrogant",
    "artful",
    "articulate",
    "artificial",
    "artistic",
    "ascetic",
    "asocial",
    "aspiring",
    "assertive",
    "astigmatic",
    "astonished",
    "atheistic",
    "athletic",
    "attentive",
    "attractive",
    "audacious",
    "austere","authentic","authoritarian","authoritative","available","average",
    "aware","awkward","babyish","bad", "balanced", "barbaric", "bashful",
    "belligerent", "benevolent", "bewildered","big-headed","big-thinking",
    "bitchy",
    "bizarre",
    "bland",
    "blasé",
    "blue",
    "blunt",
    "boastful",
    "boisterous",
    "bold",
    "bone-idle",
    "boorish",
    "bored",
    "boring",
    "bossy",
    "boyish",
    "bragging",
    "brainy",
    "brave",
    "brazen",
    "breezy",
    "bright",
    "brilliant",
    "brittle",
    "broad-minded",
    "brutal",
    "brutish",
    "businesslike",
    "busy",
    "calculating",
    "callous",
    "calm",
    "candid",
    "cantankerous",
    "capable",
    "captivating",
    "carefree",
    "careful",
    "careless",
    "caring",
    "casual",
    "caustic",
    "cautious",
    "cerebral",
    "challenge-loving",
    "challenging",
    "changeable",
    "chaotic",
    "charismatic",
    "charitable",
    "charming",
    "charmless",
    "chaste",
    "cheerful",
    "childish",
    "choosy",
    "chummy",
    "circumspect",
    "civilized",
    "classy",
    "clean",
    "clean-cut",
    "clear-headed",
    "clever",
    "clinging",
    "clownish",
    "clumsy",
    "coarse",
    "cocky",
    "cognizant",
    "cold",
    "cold-hearted",
    "colorful",
    "colorless",
    "comforting",
    "comical",
    "committed",
    "communicative",
    "companionable",
    "compassionate",
    "competent",
    "competitive",
    "complacent",
    "complaining",
    "complaintive",
    "complex",
    "compliant",
    "composed",
    "compulsive",
    "conceited",
    "concerned",
    "conciliatory",
    "condemnatory",
    "condescending",
    "confident",
    "confidential",
    "conforming",
    "conformist",
    "confrontational", "confused","congenial","conscientious","conservative","considerate","consistent",
    "constant",
    "constructive",
    "contemplative",
    "contemptible",
    "content",
    "contented",
    "contradictory",
    "contrite",
    "controlling",
    "conventional",
    "convincing",
    "convivial",
    "cool-headed",
    "cooperative",
    "cordial",
    "courageous",
    "courteous",
    "coward",
    "cowardly",
    "crafty",
    "cranky",
    "crass",
    "crazy",
    "creative",
    "criminal",
    "crisp",
    "critical",
    "cross",
    "crude",
    "cruel",
    "cultured",
    "cunning",
    "curious",
    "cute",
    "cynical",
    "daffy",
    "dainty",
    "dangerous",
    "daring",
    "dark",
    "dauntless",
    "daydreamer",
    "debonair",
    "decadent",
    "deceitful","decent","deceptive","decisive",
    "dedicated",
    "deep",
    "deferential",
    "defiant",
    "deliberate",
    "delicate",
    "demanding",
    "dependable",
    "dependent",
    "depressed",
    "desiccated",
    "desperate",
    "despicable",
    "despondent",
    "destructive",
    "detached",
    "determined",
    "devious",
    "devoted",
    "difficult",
    "dignified",
    "diligent",
    "dim-witted",
    "diplomatic",
    "direct",
    "directed",
    "dirty",
    "disaffected",
    "disagreeable",
    "discerning",
    "disciplined",
    "disconcerting",
    "discontent",
    "discontented",
    "discouraged",
    "discouraging",
    "discourteous",
    "discreet",
    "discriminating",
    "disgusting",
    "dishonest",
    "dishonorable",
    "disillusioned",
    "dislikeable",
    "disloyal",
    "dismayed",
    "disobedient",
    "disorderly",
    "disorganized",
    "disparaging",
    "disputatious",
    "disrespectful",
    "disruptive",
    "dissatisfied",
    "dissolute",
    "dissonant",
    "distant",
    "distractable",
    "distraught",
    "distressed",
    "distrustful",
    "disturbed",
    "disturbing",
    "dogmatic",
    "dominating",
    "domineering",
    "doubtful",
    "dowdy",
    "down-hearted",
    "downtrodden",
    "dramatic",
    "dreamy",
    "driving",
    "droll",
    "dry",
    "dull",
    "dumb",
    "dutiful",
    "dynamic",
    "eager",
    "earnest",
    "earthy",
    "easily discouraged",
    "easy-going",
    "ebullient",
    "eccentric",
    "eclectic",
    "educated",
    "effective",
    "effeminate",
    "effervescent",
    "efficient",
    "egocentric",
    "egotistic",
    "egotistical",
    "elegant",
    "eloquent",
    "elusive",
    "embarrassed",
    "embittered",
    "emotional",
    "empathetic",
    "encouraging",
    "energetic",
    "enervated",
    "engaged",
    "enigmatic",
    "enterprising",
    "entertaining",
    "enthused",
    "enthusiastic",
    "envious",
    "equable",
    "equitable",
    "erratic",
    "escapist",
    "ethical",
    "evil",
    "exacting",
    "exaggerated",
    "excessive",
    "excitable",
    "excited",
    "exciting",
    "exotic",
    "expedient",
    "experienced",
    "experimental",
    "expressive",
    "extraordinary",
    "extravagant",
    "extreme",
    "extroverted",
    "exuberant",
    "facetious",
    "fair",
    "fair-minded",
    "faithful",
    "faithless",
    "false",
    "familial",
    "fanatical",
    "fanciful",
    "fancy",
    "far-sighted",
    "fashionable",
    "fatalistic",
    "fault-finding",
    "fawning",
    "fearful",
    "fearless",
    "feisty",
    "felicific",
    "ferocious",
    "fickle",
    "fidelious",
    "fidgety",
    "fierce",
    "fiery",
    "finicky",
    "firm",
    "fixed",
    "flamboyant",
    "flexible",
    "flippant",
    "flirtatious",
    "flustered",
    "focused",
    "folksy",
    "foolhardy",
    "foolish",
    "forceful",
    "forgetful",
    "forgiving",
    "formal",
    "forthright",
    "fortunate",
    "forward",
    "foul",
    "fragile",
    "frank",
    "fraudulent",
    "free-wheeling",
    "free-thinking",
    "fresh",
    "friendly",
    "frightened",
    "frightening",
    "frigid",
    "frivolous",
    "frugal",
    "frustrated",
    "fun-loving",
    "funny",
    "furious",
    "fussy",
    "gallant",
    "garrulous",
    "gaudy",
    "gay",
    "generous",
    "gentle",
    "genuine",
    "giddy",
    "gives up easily",
    "giving",
    "glamorous",
    "gloomy",
    "glum",
    "goal-oriented",
    "godly",
    "good",
    "good-humored",
    "good-natured",
    "good-tempered",
    "gossipy",
    "graceful",
    "graceless",
    "gracious",
    "grand",
    "grandiose",
    "grateful",
    "greedy",
    "gregarious",
    "grim",
    "grotesque",
    "grouchy",
    "grumpy",
    "guileless",
    "guilty",
    "gullible",
    "haggard",
    "happy",
    "hard-hearted",
    "hard-working",
    "hardy",
    "harried",
    "harsh",
    "hateful",
    "haughty",
    "headstrong",
    "healthy",
    "heartbroken",
    "heartless",
    "hearty",
    "hedonistic",
    "helpful",
    "helpless",
    "heroic",
    "hesitant",
    "hidebound",
    "high-handed",
    "high-minded",
    "high-spirited",
    "high-strung",
    "holy",
    "honest",
    "honorable",
    "hopeful",
    "hopeless",
    "hospitable",
    "hostile",
    "hot-headed",
    "hot-tempered",
    "humble",
    "humorless",
    "humorous",
    "hurried",
    "hypnotic",
    "hypochondriacal",
    "hypocritical",
    "hysterical",
    "iconoclastic",
    "idealistic",
    "idiosyncratic",
    "idiotic",
    "ignorant",
    "ill-bred",
    "ill-mannered",
    "ill-tempered",
    "illogical",
    "imaginative",
    "imitative",
    "immaculate",
    "immature",
    "immobile",
    "immodest",
    "impartial",
    "impassive",
    "impatient",
    "impeccable",
    "impersonal",
    "impolite",
    "impractical",
    "impressionable",
    "impressive",
    "imprudent",
    "impudent",
    "impulsive",
    "inaccurate",
    "inactive",
    "inattentive",
    "incisive",
    "incoherent",
    "incompetent",
    "inconsiderate",
    "inconsistent",
    "incorruptible",
    "incurious",
    "indecisive",
    "independent",
    "indifferent",
    "indiscreet",
    "indiscriminate",
    "individualistic",
    "indolent",
    "indulgent",
    "industrious",
    "inefficient",
    "inept",
    "inert",
    "inexperienced",
    "infantile",
    "inflexible",
    "informal",
    "informed",
    "ingenious",
    "inhibited",
    "inhumane",
    "inimitable",
    "innocent",
    "innovative",
    "inoffensive",
    "inquisitive",
    "insecure",
    "insensitive",
    "insightful",
    "insincere",
    "insipid",
    "insistent",
    "insolent",
    "insouciant",
    "insulting",
    "intellectual",
    "intelligent",
    "intense",
    "interesting",
    "interfering",
    "intimidating",
    "intolerant",
    "intrepid",
    "introspective",
    "introverted",
    "intuitive",
    "inventive",
    "invisible",
    "invulnerable",
    "irascible",
    "irrational",
    "irreligious",
    "irresponsible",
    "irreverent",
    "irritable",
    "irritating",
    "jealous",
    "jolly",
    "jovial","joyful","judgemental","jumpy",
    "just",
    "keen",
    "kind",
    "kind-hearted",
    "kindly",
    "knowledgeable",
    "lackadaisical",
    "languid",
    "lascivious",
    "lazy",
    "leaderly",
    "left-brain",
    "leisurely",
    "lethargic",
    "level-headed",
    "lewd",
    "liberal",
    "libidinous",
    "licentious",
    "lifeless",
    "light",
    "light-hearted",
    "likeable",
    "limited",
    "listless",
    "literary",
    "lively",
    "logical",
    "lonely",
    "lonesome",
    "loquacious",
    "loud",
    "loud-mouthed",
    "lovable",
    "challenge-loving",
    "challenged",
    "loving",
    "loyal",
    "lucky",
    "lyrical",
    "machiavellian",
    "macho",
    "magnanimous",
    "maladjusted",
    "malicious",
    "maniacal",
    "manipulative",
    "mannerless",
    "mannered",
    "mannerly",
    "many-sided",
    "masculine/manly",
    "masochistic",
    "materialistic",
    "maternal",
    "mathematical",
    "mature",
    "mawkish",
    "mealy-mouthed",
    "mean",
    "mechanical",
    "meddlesome",
    "mediocre",
    "meditative",
    "meek",
    "melancholic",
    "melancholy",
    "mellow",
    "melodramatic",
    "merciful",
    "meretricious",
    "messy",
    "methodical",
    "meticulous",
    "mischievous",
    "miserable",
    "miserly",
    "misfit",
    "misguided",
    "mistaken",
    "moderate",
    "modern",
    "modest",
    "money-minded",
    "monstrous",
    "moody",
    "moral",
    "moralistic",
    "morbid",
    "muddle-headed",
    "multi-levelled",
    "mundane",
    "mysterious",
    "mystical",
    "nagging",
    "naive",
    "narcissistic",
    "narrow-minded",
    "nasty",
    "natty",
    "naughty",
    "naïve",
    "neat",
    "negative",
    "neglectful",
    "negligent",
    "nervous",
    "neurotic",
    "neutral",
    "nice",
    "nihilistic",
    "noble",
    "noisy",
    "non-authoritarian",
    "non-committal",
    "non-committing",
    "non-competitive",
    "nonchalant",
    "nonconforming",
    "normal",
    "nosey",
    "nostalgic",
    "nurturing",
    "obedient",
    "obese",
    "objective",
    "obliging",
    "obnoxious",
    "obscene",
    "obsequious",
    "observant",
    "obsessive",
    "obstinate",
    "obvious",
    "odd",
    "offensive",
    "offhand",
    "old-fashioned",
    "one-dimensional",
    "one-sided",
    "open",
    "open-minded",
    "opinionated",
    "opportunistic",
    "optimistic",
    "orderly",
    "ordinary",
    "organized",
    "original",
    "ornery",
    "outgoing",
    "outrageous",
    "outspoken",
    "outstanding",
    "over-imaginative",
    "overbearing",
    "overcautious",
    "overconfident",
    "overcritical",
    "overemotional",
    "oversensitive",
    "painstaking",
    "pandemonious",
    "paranoid",
    "parsimonious",
    "passionate",
    "passive",
    "paternalistic",
    "patient",
    "patriotic",
    "patronizing",
    "peaceful",
    "pedantic",
    "pensive",
    "perceptive",
    "perfectionistic",
    "perseverant",
    "persevering",
    "persistent",
    "personable",
    "persuasive",
    "pert",
    "perverse",
    "perverted",
    "pessimistic",
    "petty",
    "petulant",
    "pharisaical",
    "philanthropic",
    "philosophical",
    "phlegmatic",
    "phony",
    "physical",
    "picky",
    "pioneering",
    "pious",
    "pitiful",
    "placid",
    "plain",
    "planful",
    "playful",
    "pleasant",
    "pleasing",
    "plodding",
    "plucky",
    "poised",
    "polished",
    "polite",
    "political",
    "pompous",
    "popular",
    "positive",
    "possessive",
    "power-hungry",
    "powerful",
    "practical",
    "precise",
    "predatory",
    "predictable",
    "prejudiced",
    "preoccupied",
    "presumptuous",
    "pretentious",
    "pretty",
    "prideful",
    "prim",
    "primitive",
    "principled",
    "private",
    "pro-active",
    "procrastinating",
    "productive",
    "profane",
    "proficient",
    "profligate",
    "profound",
    "progressive",
    "promiscuous",
    "prompt",
    "proper",
    "prosaic",
    "protean",
    "protective",
    "proud",
    "provident",
    "providential",
    "provocative",
    "prudent",
    "psychopathic",
    "psychotic",
    "pugnacious",
    "punctilious",
    "punctual",
    "pure",
    "puritanical",
    "purposeful",
    "purposeless",
    "pushy",
    "pusillanimous",
    "puzzled",
    "quarrelsome",
    "questioning",
    "quick-tempered",
    "quick-witted",
    "quiet",
    "quirky",
    "quixotic",
    "radical",
    "rambunctious",
    "rash",
    "rational",
    "reactionary",
    "reactive",
    "realistic",
    "reasonable",
    "rebellious",
    "reckless",
    "reclusive",
    "refined",
    "reflective",
    "regimental",
    "regretful",
    "relaxed",
    "reliable",
    "relieved",
    "religious",
    "remorseful",
    "remote",
    "repentant",
    "repressed",
    "repugnant",
    "repulsive",
    "resentful",
    "reserved",
    "resigned",
    "resilient",
    "resourceful",
    "respectable",
    "respectful",
    "responsible",
    "responsive",
    "restless",
    "restrained",
    "reverential",
    "rich",
    "ridiculous",
    "righteous",
    "rigid",
    "risk-taking",
    "ritualistic",
    "romantic",
    "rough",
    "rough-around-the-edges",
    "rowdy",
    "rude",
    "ruined",
    "rustic",
    "ruthless",
    "sad",
    "sadistic",
    "safe",
    "sage",
    "saintly",
    "sanctimonious",
    "sane",
    "sarcastic",
    "sassy",
    "satirical",
    "satisfied",
    "saucy",
    "saving",
    "savvy",
    "scared",
    "scatty",
    "scheming",
    "scholarly",
    "scientific",
    "scolding",
    "scornful",
    "scrupulous",
    "secretive",
    "secure",
    "sedate",
    "sedentary",
    "self-absorbed",
    "self-assured",
    "self-centered",
    "self-conceited",
    "self-concerned",
    "self-confident",
    "self-conscious",
    "self-contented",
    "self-controlled",
    "self-controlling",
    "self-critical",
    "self-defacing",
    "self-denying",
    "self-disciplined",
    "self-effacing",
    "self-indulgent",
    "self-possessed",
    "self-reliant",
    "self-righteous",
    "self-satisfied",
    "self-sufficient",
    "selfish",
    "selfless",
    "senile",
    "sensible",
    "sensitive",
    "sensual",
    "sentimental",
    "seraphic",
    "serene",
    "serious",
    "sexy",
    "shallow",
    "sharing",
    "sharp",
    "sharp-witted",
    "sheepish",
    "shiftless",
    "short-sighted",
    "short-tempered",
    "showy",
    "shrewd",
    "shy",
    "silent",
    "silly",
    "simple",
    "simple-minded",
    "sincere",
    "single-minded",
    "skeptical",
    "sceptical",
    "skilful",
    "skillful",
    "skilled",
    "sleazy",
    "sloppy",
    "slovenly",
    "slow",
    "sluggish",
    "sly",
    "small-thinking",
    "smart",
    "smooth",
    "smug",
    "sneaky",
    "snobbish",
    "snobby",
    "sober",
    "sociable",
    "social",
    "soft",
    "soft-headed",
    "soft-hearted",
    "soft-spoken",
    "solemn",
    "solid",
    "solitary",
    "sophisticated",
    "sordid",
    "sorry",
    "sparing",
    "spirited",
    "spiritual",
    "spiteful",
    "spoiled",
    "spontaneous",
    "sporting",
    "sportsmanlike",
    "squeamish",
    "stable",
    "steadfast",
    "steady",
    "steely",
    "sterile",
    "stern",
    "stiff",
    "stingy",
    "stoic",
    "stoical",
    "stolid",
    "straight-laced",
    "straightforward",
    "strange",
    "strict",
    "strong-minded",
    "strong-willed",
    "stubborn",
    "studious",
    "stupid",
    "stylish",
    "suave",
    "subjective",
    "submissive",
    "subtle",
    "successful",
    "sullen", "sulky",
    "supercilious",
    "superficial",
    "superstitious",
    "supportive",
    "surly",
    "surprising",
    "suspicious",
    "sweet",
    "sympathetic",
    "systematic",
    "taciturn",
    "tactful",
    "tactless",
    "talented",
    "talkative",
    "tardy",
    "tasteful",
    "tasteless",
    "teacherly",
    "telepathic",
    "temperamental",
    "temperate",
    "tenacious",
    "tender",
    "tense",
    "tentative",
    "terrified",
    "thankful",
    "theatrical",
    "thievish",
    "thorough",
    "thoughtful",
    "thoughtless",
    "thrifty",
    "thrilled",
    "thrilling",
    "tidy",
    "timid",
    "tired",
    "tireless",
    "tiresome",
    "tolerant",
    "tomboyish",
    "touchy",
    "tough",
    "tractable",
    "traitorous",
    "transparent",
    "treacherous",
    "trendy",
    "trivial",
    "troubled",
    "troublesome",
    "truculent",
    "trustful",
    "trusting",
    "trustworthy",
    "truthful",
    "tyrannical",
    "ultra-critical",
    "unaccommodating",
    "unadventurous",
    "unaggressive",
    "unagreeable",
    "unambitious",
    "unappealing",
    "unappreciative",
    "unapproachable",
    "unassuming",
    "unaware",
    "uncaring",
    "unceremonious",
    "unchanging",
    "uncharitable",
    "uncivil",
    "unclean",
    "uncommunicative",
    "uncomplaining",
    "uncompromising",
    "unconcerned",
    "uncongenial",
    "uncontrolled",
    "unconventional",
    "unconvincing",
    "uncooperative",
    "uncoordinated",
    "uncouth",
    "uncreative",
    "uncritical",
    "unctuous",
    "uncultured",
    "undecided",
    "undemanding",
    "undependable",
    "underhanded",
    "understanding",
    "undisciplined",
    "undogmatic",
    "uneducated",
    "uneasy",
    "unemotional",
    "unenterprising",
    "unentertaining",
    "unenthusiastic",
    "unethical",
    "unfair",
    "unfathomable",
    "unfoolable",
    "unforgiving",
    "unfriendly",
    "ungraceful",
    "ungracious",
    "ungrateful",
    "unhappy",
    "unhurried",
    "unimaginative",
    "unimpressive",
    "unindustrious",
    "uninhibited",
    "uninquisitive",
    "uninspiring",
    "unintellectual",
    "unintelligent",
    "uninteresting",
    "unkind",
    "unkindly",
    "unlovable",
    "unlucky",
    "unmerciful",
    "unmethodical",
    "unmotivated",
    "unnatural",
    "unobliging",
    "unobservant",
    "unoriginal",
    "unpatriotic",
    "unpleasant",
    "unpleasing",
    "unpoised",
    "unpolished",
    "unpopular",
    "unpredictable",
    "unprincipled",
    "unproductive",
    "unpunctual",
    "unrealistic",
    "unreasonable",
    "unrefined",
    "unreflective",
    "unreliable",
    "unreligious",
    "unrestrained",
    "unromantic",
    "unruly",
    "unscrupulous",
    "unselfish",
    "unsentimental",
    "unskilled",
    "unsociable",
    "unsocial",
    "unsophisticated",
    "unsporting",
    "unsportsmanlike",
    "unstable",
    "unstudious",
    "unsuitable",
    "unsympathetic",
    "unsystematic",
    "untidy",
    "untiring",
    "untrustworthy",
    "untruthful",
    "unwise",
    "upright",
    "glad", "green",
    "upset",
    "urbane",
    "useful",
    "vacant",
    "vacuous",
    "vague",
    "vain",
    "valiant",
    "venal",
    "vengeful",
    "venomous",
    "venturesome",
    "verbose",
    "versatile",
    "vigorous",
    "vindictive",
    "violent",
    "virtuous",
    "vivacious",
    "vulnerable",
    "warm",
    "warm-hearted",
    "wasteful",
    "weak",
    "weak-willed",
    "weird",
    "well-bred",
    "well-groomed",
    "well-mannered",
    "well-meaning",
    "well-read",
    "well-rounded",
    "well-spoken",
    "whimsical",
    "wholesome",
    "wicked",
    "wild",
    "wilful",
    "willing",
    "winning",
    "wise",
    "wishful",
    "wishy-washy",
    "withdrawing",
    "withdrawn","witty","wordy","long", "long-winded", "worldly",
    "worried","worrying","wrong","youthful","zany","zealous"};

char *nouns[]  = {
    "people", "history", "way", 
    "art", "world", "information", 
    "map", "family", 
    "government", "health", "system", 
    "computer", "meat", "year", 
    "thanks", "music", "person", 
    "reading", "method", "data", 
    "food", "understanding", "theory", 
    "law", "bird", "literature", 
    "problem", "software", "control", 
    "knowledge", "power", "ability", 
    "economics", "love", "internet", 
    "television", "science", "library", 
    "nature", "fact", "product", 
    "idea", "temperature", "investment", 
    "area", "society", "activity", 
    "story", "industry", "media", 
    "thing", "oven", "community", 
    "definition", "safety", "quality", 
    "development", "language", "management", 
    "player", "variety", "video", 
    "week", "security", "country", 
    "exam", "movie", "organization", 
    "equipment", "physics", "analysis", 
    "policy", "series", "thought", 
    "basis", "boyfriend", "direction", 
    "strategy", "technology", "army", 
    "camera", "freedom", "paper", 
    "environment", "child", "instance", 
    "month", "truth", "marketing", 
    "university", "writing", "article", 
    "department", "difference", "goal", 
    "news", "audience", "fishing", 
    "growth", "income", "marriage", 
    "user", "combination", "failure", 
    "meaning", "medicine", "philosophy", 
    "teacher", "communication", "night", 
    "chemistry", "disease", "disk", 
    "energy", "nation", "road", 
    "role", "soup", "advertising", 
    "location", "success", "addition", 
    "apartment", "education", "math", 
    "moment", "painting", "politics", 
    "attention", "decision", "event", 
    "property", "shopping", "student", 
    "wood", "competition", "distribution", 
    "entertainment", "office", "population", 
    "president", "unit", "category", 
    "cigarette", "context", "introduction", 
    "opportunity", "performance", "driver", 
    "flight", "length", "magazine", 
    "newspaper", "relationship", "teaching", 
    "cell", "dealer", "finding", 
    "lake", "member", "message", 
    "phone", "scene", "appearance", 
    "association", "concept", "customer", 
    "death", "discussion", "housing", 
    "inflation", "insurance", "mood", 
    "woman", "advice", "blood", 
    "effort", "expression", "importance", 
    "opinion", "payment", "reality", 
    "responsibility", "situation", "skill", 
    "statement", "wealth", "application", 
    "city", "county", "depth", 
    "estate", "foundation", "grandmother", 
    "heart", "perspective", "photo", 
    "recipe", "studio", "topic", "wolf",
    "collection", "depression", "imagination", 
    "passion", "percentage", "resource", 
    "setting", "ad", "agency", 
    "college", "connection", "criticism", 
    "debt", "description", "memory", 
    "patience", "secretary", "solution", 
    "administration", "aspect", "attitude", 
    "director", "personality", "psychology", 
    "recommendation", "response", "selection", 
    "storage", "version", "alcohol", "hero",
    "argument", "complaint", "contract", 
    "emphasis", "highway", "loss", 
    "membership", "possession", "preparation", 
    "steak", "union", "agreement", 
    "cancer", "currency", "employment", 
    "engineering", "entry", "interaction", 
    "mixture", "preference", "region", 
    "republic", "tradition", "virus", 
    "actor", "classroom", "delivery", 
    "device", "difficulty", "drama", 
    "election", "engine", "football", 
    "guidance", "hotel", "owner", 
    "priority", "protection", "suggestion", 
    "tension", "variation", "anxiety", 
    "atmosphere", "awareness", "bath", 
    "bread", "candidate", "climate", 
    "comparison", "confusion", "construction", 
    "elevator", "emotion", "employee", 
    "employer", "guest", "height", 
    "leadership", "mall", "manager", 
    "operation", "recording", "sample", 
    "transportation", "charity", "cousin", 
    "disaster", "editor", "efficiency", 
    "excitement", "extent", "feedback", 
    "guitar", "homework", "leader", 
    "mom", "outcome", "permission", 
    "presentation", "promotion", "reflection", 
    "refrigerator", "resolution", "revenue", 
    "session", "singer", "tennis", 
    "basket", "bonus", "cabinet", 
    "childhood", "church", "clothes", 
    "coffee", "dinner", "drawing", 
    "hair", "hearing", "initiative", 
    "judgment", "lab", "measurement", 
    "mode", "mud", "orange", 
    "poetry", "police", "possibility", 
    "procedure", "queen", "ratio", 
    "relation", "restaurant", "satisfaction", 
    "sector", "signature", "significance", 
    "song", "tooth", "town", 
    "vehicle", "volume", "wife", 
    "accident", "airport", "appointment", 
    "arrival", "assumption", "baseball", 
    "chapter", "committee", "conversation", 
    "database", "enthusiasm", "error", 
    "explanation", "farmer", "gate", 
    "girl", "hall", "historian", 
    "hospital", "injury", "instruction", 
    "maintenance", "manufacturer", "meal", 
    "perception", "pie", "poem", 
    "presence", "proposal", "reception", 
    "replacement", "revolution", "river", 
    "son", "speech", "tea", 
    "village", "warning", "winner", 
    "worker", "writer", "assistance", 
    "breath", "buyer", "chest", 
    "chocolate", "conclusion", "contribution", 
    "cookie", "courage", "dad", 
    "desk", "drawer", "establishmen", 
    "examination", "garbage", "grocery", 
    "honey", "impression", "improvement", 
    "independence", "insect", "inspection", 
    "inspector", "king", "ladder", 
    "menu", "penalty", "piano", 
    "potato", "profession", "professor", 
    "quantity", "reaction", "requirement", 
    "salad", "sister", "supermarket", 
    "tongue", "weakness", "wedding", 
    "affair", "ambition", "analyst", 
    "apple", "assignment", "assistant", 
    "bathroom", "bedroom", "beer", 
    "birthday", "celebration", "championship", 
    "cheek", "client", "consequence", 
    "departure", "diamond", "dirt", 
    "ear", "fortune", "friendship", 
    "funeral", "gene", "girlfriend", 
    "hat", "indication", "intention", 
    "lady", "midnight", "negotiation", 
    "obligation", "passenger", "pizza", 
    "platform", "poet", "pollution", 
    "recognition", "reputation", "shirt", 
    "sir", "speaker", "stranger", 
    "surgery", "sympathy", "tale", 
    "throat", "trainer", "uncle", 
    "youth", "time", "work", 
    "film", "water", "money", 
    "example", "while", "business", 
    "study", "game", "life", 
    "form", "air", "day", 
    "place", "number", "part", 
    "field", "fish", "back", 
    "process", "heat", "hand", 
    "experience", "job", "book", 
    "end", "point", "type", 
    "home", "economy", "value", 
    "body", "market", "guide", 
    "interest", "state", "radio", 
    "course", "company", "price", 
    "size", "card", "list", 
    "mind", "trade", "line", 
    "care", "group", "risk", 
    "word", "fat", "force", 
    "key", "light", "training", 
    "name", "school", "top", 
    "amount", "level", "order", 
    "practice", "research", "sense", 
    "service", "piece", "web",
    "boss", "sport", "fun",
    "house", "page", "term",
    "test", "answer", "sound",
    "focus", "matter", "kind",
    "soil", "board", "oil",
    "picture", "access", "garden","ranger"
    "range", "rate", "reason",
    "future", "site", "demand",
    "exercise", "image", "case",
    "cause", "coast", "action",
    "age", "bad", "boat",
    "record", "result", "section",
    "building", "mouse", "cash",
    "class", "nothing", "period",
    "plan", "store", "tax",
    "side", "subject", "space",
    "rule", "stock", "weather",
    "chance", "figure", "man",
    "model", "source", "beginning",
    "earth", "program", "chicken",
    "design", "feature", "head",
    "material", "purpose", "question",
    "rock", "salt", "act",
    "birth", "car", "dog",
    "object", "scale", "sun",
    "note", "profit", "rent",
    "speed", "style", "war",
    "bank", "craft", "half",
    "inside", "outside", "standard",
    "bus", "exchange", "eye",
    "fire", "position", "pressure",
    "stress", "advantage", "benefit",
    "box", "frame", "issue",
    "step", "cycle", "face",
    "item", "metal", "paint",
    "review", "room", "screen",
    "structure", "view", "account",
    "ball", "discipline", "medium",
    "share", "balance", "bit",
    "black", "bottom", "choice",
    "gift", "impact", "machine",
    "shape", "tool", "wind",
    "address", "average", "career",
    "culture", "morning", "pot",
    "sign", "table", "task",
    "condition", "contact", "credit",
    "egg", "hope", "ice",
    "network", "north", "square",
    "attempt", "date", "effect",
    "link", "post", "star",
    "voice", "capital", "challenge",
    "friend", "self", "shot",
    "brush", "couple", "debate",
    "exit", "front", "function",
    "lack", "living", "plant",
    "plastic", "spot", "summer",
    "taste", "theme", "track",
    "wing", "brain", "button",
    "click", "desire", "foot",
    "gas", "influence", "notice",
    "rain", "wall", "base",
    "damage", "distance", "feeling",
    "pair", "savings", "staff",
    "sugar", "target", "text",
    "animal", "author", "budget",
    "discount", "file", "ground",
    "lesson", "minute", "officer",
    "phase", "reference", "register",
    "sky", "stage", "stick",
    "title", "trouble", "bowl",
    "bridge", "campaign", "character",
    "club", "edge", "evidence",
    "fan", "letter", "lock",
    "maximum", "novel", "option",
    "pack", "park", "plenty",
    "quarter", "skin", "sort",
    "weight", "baby", "background",
    "carry", "dish", "factor",
    "fruit", "glass", "joint",
    "master", "muscle", "red", "green"
    "strength", "traffic", "trip",
    "vegetable", "appeal", "chart",
    "gear", "ideal", "kitchen",
    "land", "log", "mother",
    "net", "party", "principle",
    "relative", "sale", "season",
    "signal", "spirit", "street",
    "tree", "wave", "belt",
    "bench", "commission", "copy",
    "drop", "minimum", "path",
    "progress", "project", "sea",
    "south", "status", "stuff",
    "ticket", "tour", "angle",
    "blue", "breakfast", "confidence",
    "daughter", "degree", "doctor",
    "dot", "dream", "duty",
    "essay", "father", "fee",
    "finance", "hour", "juice",
    "limit", "luck", "milk",
    "mouth", "peace", "pipe",
    "seat", "stable", "storm",
    "substance", "team", "trick",
    "afternoon", "bat", "beach",
    "blank", "catch", "chain",
    "consideratio", "cream", "crew",
    "detail", "gold", "interview",
    "kid", "mark", "match",
    "mission", "pain", "pleasure",
    "score", "screw", "screwdriver",
    "shop", "shower", "suit",
    "tone", "window", "agent",
    "band", "block", "bone",
    "calendar", "cap", "coat",
    "contest", "corner", "court",
    "cup", "district", "door",
    "east", "finger", "garage",
    "guarantee", "hole", "hook",
    "implement", "layer", "lecture",
    "lie", "manner", "meeting",
    "nose", "parking", "partner",
    "profile", "respect", "rice",
    "routine", "schedule", "swimming",
    "telephone", "tip", "winter",
    "airline", "bag", "battle",
    "bed", "bill", "bother",
    "cake", "code", "curve",
    "designer", "dimension", "dress",
    "ease", "emergency", "evening",
    "extension", "farm", "fight",
    "gap", "grade", "holiday",
    "horror", "horse", "host",
    "husband", "loan", "mistake",
    "mountain", "nail", "noise",
    "occasion", "package", "patient",
    "pause", "phrase", "proof",
    "race", "relief", "sand",
    "sentence", "shoulder", "smoke",
    "stomach", "string", "tourist",
    "towel", "vacation", "west",
    "wheel", "wine", "arm",
    "aside", "associate", "bet",
    "blow", "border", "branch",
    "breast", "brother", "buddy",
    "bunch", "chip", "coach",
    "cross", "document", "draft",
    "dust", "expert", "floor",
    "god", "golf", "habit",
    "iron", "judge", "knife",
    "landscape", "league", "mail",
    "mess", "native", "opening",
    "parent", "pattern", "pin",
    "pool", "pound", "request",
    "salary", "shame", "shelter",
    "shoe", "silver", "tackle",
    "tank", "trust", "assist",
    "bake", "bar", "bell",
    "bike", "blame", "boy",
    "brick", "chair", "closet",
    "clue", "collar", "comment",
    "conference", "devil", "diet",
    "fear", "fuel", "glove",
    "jacket", "lunch", "monitor",
    "mortgage", "nurse", "pace",
    "panic", "peak", "plane",
    "reward", "row", "sandwich",
    "shock", "spite", "spray",
    "surprise", "till", "transition",
    "weekend", "welcome", "yard",
    "alarm", "bend", "bicycle",
    "bite", "blind", "bottle",
    "cable", "candle", "clerk",
    "cloud", "concert", "counter",
    "flower", "grandfather", "harm",
    "knee", "lawyer", "leather",
    "load", "mirror", "neck",
    "pension", "plate", "purple",
    "ruin", "ship", "skirt",
    "slice", "snow", "specialist",
    "stroke", "switch", "trash",
    "tune", "zone", "anger",
    "award", "bid", "bitter",
    "boot", "bug", "camp",
    "candy", "carpet", "cat",
    "champion", "channel", "clock",
    "comfort", "cow", "crack","parrot"
    "engineer", "entrance", "fault",
    "grass", "guy", "hell",
    "highlight", "incident", "island",
    "joke", "jury", "leg",
    "lip", "mate", "motor",
    "nerve", "passage", "pen",
    "pride", "priest", "prize",
    "promise", "resident", "resort",
    "ring", "roof", "rope",
    "sail", "scheme", "script",
    "sock", "station", "toe",
    "tower", "truck", "witness",
    "can", "will", "if",
    "one", "many", "most",
    "other", "use", "make",
    "good", "look", "help",
    "go", "great", "being",
    "few", "might", "still",
    "public", "read", "keep",
    "start", "give", "human",
    "local", "general", "she",
    "specific", "play",
    "feel", "high", "tonight",
    "change", "simple", "past",  
    "major", "personal", 
    "current", "national", "cut", 
    "natural", "physical", "show", 
    "try", "check", "second", 
    "call", "move", "pay", 
    "let", "increase", "single", 
    "individual", "turn", "ask", "turtle",
    "buy", "guard", "hold", "claw",
    "main", "offer", "potential", "raven",
    "professional", "internationa", "travel", 
    "cook", "alternative", "following", 
    "special", "working", "whole", 
    "dance", "excuse", "cold", 
    "commercial", "low", "purchase", 
    "deal", "primary", "worth", 
    "fall", "necessary", "positive", 
    "produce", "search", "present", 
    "spend", "talk", 
    "tell", "cost", "drive", 
    "support",  "duck",
    "remove", "return", "run", 
    "complex", "due", "effective", 
    "middle", "regular", "reserve", 
    "independent", "leave", "original", 
    "reach", "rest", "serve", 
    "watch", "beautiful", "charge", 
    "active", "break", "negative", 
    "safe", "stay", "visit", 
    "visual", "affect", "cover", 
    "report", "rise", "walk", 
    "white", "beyond", "junior", 
    "pick", "unique", "anything", 
    "classic", "final", "lift", 
    "mix", "private", "stop", 
    "teach", "western", "concern", 
    "familiar", "fly", "official", 
    "broad", "comfortable", "gain", 
    "maybe", "rich", "save", 
    "stand", "young", "fail", 
    "heavy", "hello", "lead", 
    "listen", "valuable", "worry", 
    "handle", "leading", "meet", 
    "release", "sell", "finish", 
    "normal", "press", "ride", 
    "secret", "spread", "spring", 
    "tough", "wait", "brown", 
    "deep", "display", "flow", 
    "hit", "objective", "shoot", 
    "touch", "cancel", "chemical", 
    "cry", "dump", "extreme", 
    "push", "conflict", "eat", 
    "fill", "formal", "jump", 
    "kick", "opposite", "pass", 
    "pitch", "remote", "total", 
    "treat", "vast", "abuse", 
    "beat", "burn", "deposit", 
    "print", "raise", "sleep", 
    "somewhere", "advance", "anywhere", 
    "consist", "dark", "double", 
    "draw", "equal", "fix", 
    "hire", "internal", "join", 
    "kill", "sensitive", "tap", 
    "win", "attack", "claim", 
    "constant", "drag", "drink", 
    "guess", "minor", "pull", 
    "raw", "soft", "solid", 
    "wear", "weird", "wonder", 
    "annual", "count", "dead", 
    "doubt", "feed", "forever", 
    "impress", "nobody", "repeat", 
    "round", "sing", "slide", 
    "strip", "whereas", "wish", 
    "combine", "command", "dig", 
    "divide", "equivalent", "hang", 
    "hunt", "initial", "march", 
    "mention", "smell", "spiritual", 
    "survey", "tie", "adult", "snake"
    "brief", "crazy", "escape", 
    "gather", "hate", "prior", 
    "repair", "rough", "sad", "soldier",
    "scratch", "sick", "strike", 
    "employ", "external", "hurt", 
    "illegal", "laugh", "lay", 
    "mobile", "nasty", "ordinary", 
    "respond", "royal", "senior", 
    "split", "strain", "struggle", 
    "swim", "train", "upper", 
    "wash", "yellow", "convert", 
    "crash", "dependent", "fold", 
    "funny", "grab", "hide", 
    "miss", "permit", "quote", 
    "recover", "resolve", "roll", 
    "sink", "slip", "spare", 
    "suspect", "sweet", "swing", 
    "twist", "upstairs", "usual", 
    "abroad", "brave", "calm", 
    "concentrate", "estimate", 
    "male", "mine", "prompt", 
    "quiet", "refuse", "regret",
    "reveal", "rush", "shake", 
    "shift", "shine", "steal", 
    "suck", "surround", "anybody", "bear", "brilliant", "dare", "dear", "delay", "drunk", 
    "hurry", "inevitable", "invite", "kiss", "neat", 
    "pop", "punch", "quit", "reply", "representative", "resist", 
    "rip", "rub",  "smile", "spell", "stretch", 
    "stupid", "tear", "temporary", "tomorrow", "wake", "wrap", 
    "yesterday", "deer"};

// tests if the string p_s starts with the string p_word
bool isMatch(const char* p_s, const char* p_word) {
    int strLen_s    = strlen(p_s);
    int strLen_word = strlen(p_word);
    for( int k = 0; k < strLen_word; k++ ) {
        if( k >= strLen_s || p_s[k] != p_word[k] ) {
            return false;
        }
    }
    return true;
}

void printUsage();

int main(int argc, char *argv[]) {
    // default pattern. Can be overwritten by command line args
    const char* pattern = "AdjectiveNounNumber4";

    // number of user names to generate. Default is 1. Can be overwritten by command line args
    int numberOfUsernamesToGenerate = 1;

    bool srandInitialized = false;

    // parse command line args
	while (1) 
  	{
		int option_index = 0;
		static struct option long_options[] = 
		{
			{"count",   required_argument, NULL, 'c'},
			{"seed",    required_argument, NULL, 's'},
			{"help",    no_argument, NULL, 'h' },
			{"version", no_argument, NULL, 'v' },
			{NULL,      0,                 NULL,  0 }
		};

		int c = getopt_long(argc, argv, "-c:s:hv", long_options, &option_index);
		if (c == -1)
			break;

		switch (c) 
		{
        case 1:
            pattern = optarg;
            break;

		case 'c':
			numberOfUsernamesToGenerate = atoi(optarg);
			break;

		case 's':
    		srand(atoi(optarg));
            srandInitialized = true;
			break;

		case 'h':
			printUsage();
			return 0;

		case 'v':
			printf("version 1.0\n");
			break;

		case '?':
			printf("Unknown option %c\n", optopt);
			break;

		case ':':
			printf("Missing option for '%c'\n", optopt);
			break;

		default:
			printf("?? getopt returned character code 0%o, %c ??\n", c, c);
		}
	}

    // size of the arrays
    size_t adjectivesCount = sizeof(adjectives)/sizeof(adjectives[0]);
    size_t nounsCount      = sizeof(nouns)/sizeof(nouns[0]);    

    // we initiate the random number generator with the current time
    if(!srandInitialized) {
        srand(time(NULL));
    }

    // generate user names by counting up to the desired number of user names
    // In each iteration, scan the pattern and replace the placeholders with random words.
    for(int count = 1; count <= numberOfUsernamesToGenerate; count++) {
        const char* ptr = pattern;
        while( ptr[0] != '\0' ) {
            char buffer[100];
            if( isMatch(ptr, "Adjective") ) {
                strncpy(buffer, adjectives[rand() % adjectivesCount], sizeof(buffer)-1);
                buffer[0] = toupper(buffer[0]);
                printf("%s", buffer);
                ptr += sizeof("Adjective")-1;
            } else if( isMatch(ptr, "adjective") ) {
                strncpy(buffer, adjectives[rand() % adjectivesCount], sizeof(buffer)-1);
                printf("%s", buffer);
                ptr += sizeof("adjective")-1;
            } else if( isMatch(ptr, "Noun") ) {
                strncpy(buffer, nouns[rand()% nounsCount], sizeof(buffer)-1);
                buffer[0] = toupper(buffer[0]);
                printf("%s", buffer);
                ptr += sizeof("Noun")-1;
            } else if( isMatch(ptr, "noun") ) {
                strncpy(buffer, nouns[rand()% nounsCount], sizeof(buffer)-1);
                printf("%s", buffer);
                ptr += sizeof("noun")-1;
            } else if( isMatch(ptr, "Number") ) {
                ptr += sizeof("Number")-1;
                // extract digits after "Number"
                int digits = ptr[0] - 48; // '0' is ascii 48
                int r = rand() % ((int)pow(10, digits));
                printf("%d", r);
                ptr += sizeof(" ")-1;
            } else {
                printf("%c", ptr[0]);
                ptr++;
            }
        }
        printf("\n");
    }
    return 0;   
}

void printUsage() {
    printf("Usage: usergen [pattern] [options]\n");
    printf("Simple user name generator. You can provide a pattern of the form\n");
    printf("$>usergen AdjectiveNumber3Noun\n");
    printf("to generate usernames as a sequence of adjective (upper case), a 3-digit number and a noun (upper case)\n");
    printf("You can can compose pattern of Adjective, adjective, Noun, noun and Number4.\n");
    printf("options:\n");
    printf("       -c, --count    number of user names to generate and print to stout\n");
    printf("       -s, --seed     seed value (int) to initialize srand(). This generates\n");
    printf("                      determenistic and reproducable results.\n");
}